---
about:
  template: jolla
  id: about-block
  image: "img/IMG_3081 (1).jpg"
  links:
    - icon: github
      text: Github
      href: https://github.com/ChiniWiniCase
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/shraddha-dumawat/
    - icon: envelope
      text: Email
      href: "mailto:sxd1055@case.edu"  
---

::: {#about-block}
:::

# Welcome to my World!

I am Shraddha Dumawat, an aspiring biomedical-informatics scientist—though right now, I’m just a (slightly confused) first-year PhD student. This website is a window into my many interests and a few of my humble strides toward goals in personalized medicine and diagnostics.

My hands each carry stories written in lines that have led me to this very moment. My rough, right hand belongs to the side that spends hours before a laptop, immersed in coding and scientific research, each keystroke driven by the ambition to build something of my own. This is the hand of the scientist, the engineer, the problem-solver—grounded and precise, pursuing a dream with a single-minded focus.

In contrast, my left hand tells of a softer, more varied journey. It’s the hand that dreamed freely, reaching for the stars and gripping the lines of endless possibilities. This hand remembers the dreams of becoming a writer, the graceful glide of a swimmer, the expression of a theater actor, the thrill of a surfer, the boundless curiosity of an aspiring astronaut, and the innocent ambitions of a little girl who saw the world as an endless expanse of wonder.

My research spans from tackling cancer to understanding neurodegenerative diseases, where I aim to integrate ethical machine learning algorithms to empower patients and physicians with precise, tailored treatments. It's a journey that marries my scientific rigor with a deep empathy for those we strive to help, bringing the hopes written in my hands to life.
Please feel free to [contact me](mailto:sxd1055@case.edu) if you have any questions or would like to discuss potential projects.


